// react/client/pages/Login.js
import reactPolymer from 'react-polymer'; //IMPORTANT: Must be imported before React.
import React, { Component } from 'react';
import { onLogin } from "../actions/login.js";
import { connect } from "react-redux";

class Login extends Component {

    constructor() {
        super();
        reactPolymer.registerAttribute('slot')
        reactPolymer.registerEvent('login-success','login-success');
    }

    componentDidMount() {        
        this.refs.frfLogin.addEventListener("login-success", this.onLogin.bind(this));
    }


    render() {
        var loginUrl = "http://localhost:3001/api/login";
        

        return (
            <div className="login">
                <link rel="import" href="static/elements/frf-login/elements.html"/>
                <link rel="import" href="static/elements/frf-login/frf-login.html"/>
                <div className="views">
                    <frf-login ref="frfLogin"                               
                               login-url={loginUrl}                                                              
                               login-success={(e)=>this.onLogin(e)}>                        
                        <span id="title">Devfest 2017</span>
                        <img slot="logo" id="logo" src="/static/images/gde.png"/>
                    </frf-login>
                </div>
            </div>
        );
    }

    onLogin(event) {
        var userInfo = event.target.userInfo.get();
        this.props.onLogin(userInfo);
        window.location.hash='/users';
    }

}

export default connect(null, { onLogin })(Login);

// angular2/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { LoginService } from '../shared/services/login.service';
@Component({
  selector: 'wcb-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginUrl;

  constructor(private router:Router, private loginService:LoginService) { 
    this.loginUrl=this.loginService.loginUrl;
  }
  

  ngOnInit() {
    
  }

  login(event){
    this.loginService.onlogin(event.detail.userInfo.get());
    this.router.navigate(['/people']);
  }

}


  
<frf-login
    [attr.login-url]="loginUrl"                               
    (login-success)="login($event)">
    <span id="title">DevFest 2017</span>
    <img slot="logo" id="logo" src="/assets/images/gde.png"/>    
</frf-login>
